#!/usr/bin/env bash
#
# Use the version of bash installed via brew

set -euf -o pipefail

echo -en "\e[36mInstalling Bash shell...\e[39m"

new_shell_path="$(brew --prefix)/bin/bash"
export new_shell_path

if ! (grep -q "${new_shell_path}" /etc/shells); then
  echo "${new_shell_path}" | sudo tee -a /etc/shells
fi

sudo chsh -s "${new_shell_path}" "$(whoami)" > /dev/null 2>&1

echo -e " \e[32mdone\e[39m"
