#!/usr/bin/env bash
#
# Alacritty
#
# This installs the configuration for alacritty

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo -en "\e[36mInstalling custom alacritty config...\e[39m "

dest_config_dir="${HOME}/.config/alacritty"
mkdir -p "${dest_config_dir}"

dest_location="${dest_config_dir}/alacritty.toml"
config_file="alacritty.toml"

ln -s \
  "${my_dir}/${config_file}" \
  "${dest_location}"

echo -e "\e[32mdone\e[39m"
