#!/bin/bash
#
# Bash it
#
# This install Bash-it, the community bash framework.

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

bashit_dir="${HOME}/.bash_it"

echo "  Installing Bash it."
pushd "${bashit_dir}" > /dev/null
  git pull || git clone https://github.com/Bash-it/bash-it.git .

  # the install script sometimes fails for reasons outside of our control,
  # in ways that doesn't affect the rest of the process, but would trigger the
  # pipefail option (yes would receive the bad signal from ./install.sh and fail
  set +o pipefail
  yes | ./install.sh
  set -o pipefail
popd

set +u

set +ef
# Shellcheck does not like following non-constant source.
# shellcheck disable=SC1090
source "${HOME}/.bash_profile"
set -e

completions_file="${my_dir}/completions"
while read -r completion; do
  [[ -z "${completion}" ]] && continue

  echo "  Enabling completion: ${completion}."
  bash-it enable completion "${completion}"
done < "${completions_file}"

aliases_file="${my_dir}/aliases"
while read -r alias; do
  [[ -z "${alias}" ]] && continue

  echo "  Enabling alias: ${alias}."
  bash-it enable alias "${alias}"
done < "${aliases_file}"

plugins_file="${my_dir}/plugins"
while read -r plugin; do
  [[ -z "${plugin}" ]] && continue

  echo "  Enabling plugin: ${plugin}."
  bash-it enable plugin "${plugin}"
done < "${plugins_file}"

echo "  Installing custom inputrc"
rm -rf "${HOME}/.inputrc"
ln -s "${my_dir}/.inputrc" "${HOME}/.inputrc"

echo "  Installing custom bash_it scripts"
# TODO: use find or ls rather than glob
rm "${HOME}/.bash_it/custom/"*
cp "${my_dir}/custom/"* "${HOME}/.bash_it/custom/"

echo "  Installing custom bash aliases etc - done."
