#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"${my_dir}/homebrew/install"
"${my_dir}/git/install"
"${my_dir}/bash-it/install"
"${my_dir}/vim/install"
"${my_dir}/osx/install"

echo "All installation scripts completed successfully"
