#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -euf -o pipefail

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"${MY_DIR}/homebrew/install"
"${MY_DIR}/git/install"
"${MY_DIR}/bash-it/install"
"${MY_DIR}/vim/install"
"${MY_DIR}/osx/install"

echo "All installation scripts completed successfully"
