[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
ignore_branches = [ "main" ]

[git_commit]
tag_disabled = false

[golang]
disabled = true

[line_break]
disabled = true

[rust]
disabled = true

[time]
disabled = false
