#!/usr/bin/env bash
#
# Powerline Status
#
# This install powerline status bar (e.g. for vim, tmux).

set -euf -o pipefail

echo -e "\e[36mInstalling powerline...\e[39m"
pip install --upgrade powerline-status
echo -e "\e[36mInstalling powerline...\e[39m \e[32mdone\e[39m"
