#!/bin/bash
#
# Vim
#
# This configures Vim using luan's vimfiles. https://github.com/luan/vimfiles

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pip3 install --upgrade pip
pip3 install --upgrade neovim

vim_dir="${HOME}/.vim"

mkdir -p "${vim_dir}"

echo "  Updating vimfiles."
pushd "${vim_dir}"
  git pull || git clone https://github.com/luan/vimfiles.git .
popd

echo "  Installing Vimfiles."
"${vim_dir}"/install

echo "  Installing custom vim configuration."
rm -rf "${HOME}/.vimrc.local"
ln -s "${my_dir}/.vimrc.local" "${HOME}/.vimrc.local"
