#!/bin/bash
#
# Vim
#
# This install Vim using luan's vimfiles. https://github.com/luan/vimfiles

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vim_dir="${HOME}/.vim"

if [[ ! -e "${vim_dir}" ]]; then
  echo "  Cloning Vimfiles."
  git clone https://github.com/luan/vimfiles.git "${vim_dir}"
else
  echo "  Updating Vimfiles."
  pushd "${vim_dir}"
    git pull
  popd
fi

echo "  Installing Vimfiles."
"${vim_dir}"/install

echo "  Installing custom vim configuration."
rm -rf "${HOME}/.vimrc.local"
ln -s "${my_dir}/.vimrc.local" "${HOME}/.vimrc.local"
