#!/usr/bin/env bash
#
# Neovim
#
# This configures Vim using luan's vimfiles. https://github.com/luan/vimfiles

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pip3 install --upgrade pip
pip3 install --upgrade neovim
pip3 install --upgrade pynvim

nvim_dir="${HOME}/.config/nvim/"

mkdir -p "${nvim_dir}"

echo "  Updating Luan's Neovim distribution."
pushd "${nvim_dir}"
git pull || git clone https://github.com/luan/nvim.git .
popd

nvim_user_dir="${nvim_dir}/user/"
mkdir -p "${nvim_user_dir}"

echo "  Installing custom vim configuration."
rm -rf "${nvim_user_dir}/before.vim"

rm -rf "${nvim_user_dir}/plug.vim"
ln -s "${my_dir}/plug.vim" "${nvim_user_dir}/plug.vim"

rm -rf "${nvim_user_dir}/after.vim"
ln -s "${my_dir}/after.vim" "${nvim_user_dir}/after.vim"
