#!/usr/bin/env bash
#
# Neovim
#
# This configures Vim using luan's vimfiles. https://github.com/luan/vimfiles

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pip3 install --upgrade pip
pip3 install --upgrade neovim

nvim_dir="${HOME}/.config/nvim"

mkdir -p "${nvim_dir}"

echo "  Updating Luan's Neovim distribution."
pushd "${nvim_dir}" > /dev/null
  git pull -q || git clone https://github.com/luan/nvim.git .
popd > /dev/null

mkdir -p "${nvim_dir}/lua/user/"

rm -rf "${nvim_dir}/lua/user/after.lua"
ln -s "${my_dir}/.config/nvim/lua/user/after.lua" "${nvim_dir}/lua/user/after.lua"

rm -rf "${nvim_dir}/lua/user/plugins.lua"
ln -s "${my_dir}/.config/nvim/lua/user/plugins.lua" "${nvim_dir}/lua/user/plugins.lua"
