#!/bin/bash
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

packages_file="${my_dir}/packages"
taps_file="${my_dir}/taps"
binaries_file="${my_dir}/cask_binaries"

# Check for Homebrew
if test ! "$(which brew)"
then
  echo "  Installing Homebrew."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "  Updating homebrew."
brew update

echo "  Installing brew cask."
brew install caskroom/cask/brew-cask || brew upgrade caskroom/cask/brew-cask

while read -r tap; do
    [[ -z "${tap}" ]] && continue

    echo "  Installing ${tap}."
    # Returns a warning (not error) if package already exists
    brew tap "${tap}"
done < "${taps_file}"

while read -r pkg; do
    [[ -z "${pkg}" ]] && continue

    echo "  Installing ${pkg}"
    # Returns a warning (not error) if package already exists
    # Explicitly do not quote the pkg because we want to pass space-separated
    # as separate args.
    # shellcheck disable=SC2086
    brew install ${pkg} || brew upgrade ${pkg}
done < "${packages_file}"

while read -r binary; do
    [[ -z "${binary}" ]] && continue

    echo "  Installing ${binary}."
    # Returns a warning (not error) if package already exists
    brew cask install "${binary}"
done < "${binaries_file}"

echo "  Upgrading packages."
brew upgrade

exit 0
