#!/usr/bin/env bash
#
# GPG
#
# This configures gpg agent etc

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo -en "\e[36mInstalling .gnupg/gpg-agent.conf...\e[39m "
rm -rf "${HOME}/.gnupg/gpg-agent.conf"
mkdir -p "${HOME}/.gnupg/"
ln -s "${my_dir}/.gnupg/gpg-agent.conf" "${HOME}/.gnupg/gpg-agent.conf"
echo -e "\e[32mdone\e[39m"
