#!/usr/bin/env bash
#
# APT
#
# This installs packages via apt

set -euf -o pipefail

echo -e "\e[36mInstalling packages...\e[39m"

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ppas_file="${my_dir}/ppas"
while read -r ppa; do
  [[ -z "${ppa}" ]] && continue

  sudo add-apt-repository -y "${ppa}"
done < "${ppas_file}"

sudo apt-get update

sudo apt-get install -y $(cat "${my_dir}/packages" )

echo -e "\e[36mInstalling packages...\e[39m \e[32mdone\e[39m"
