#!/usr/bin/env bash
#
# Fish
#
# This install Fish

set -euf -o pipefail

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dest_location="${HOME}/.config/fish/config.fish"

echo -en "\e[36mInstalling custom Fish config...\e[39m "
rm -rf "${dest_location}"
ln -s "${my_dir}/config.fish" "${dest_location}"
echo -e "\e[32mdone\e[39m"
